version: '3'
services:
  node-app:
    build:
      context: .
      dockerfile: nodeApplication/dockerfile
    ports:
      - "4000:80"
    image: node-app:${BUILD_NUMBER}
    container_name: node-app_${BUILD_NUMBER}
  web:
    build:
      context: .
      dockerfile: reactApplication/Dockerfile.dev
    ports:
      - "3000:3000"
    volumes:
      - /usr/app/node_modules
      - .:/usr/app
